"""new model learningpath, update course model and create N:N table

Revision ID: 4708fbd16f1f
Revises: caeb5670b033
Create Date: 2026-06-10 20:23:23.502240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4708fbd16f1f'
down_revision: Union[str, Sequence[str], None] = 'caeb5670b033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_path',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('link_image', sa.String(length=255), nullable=False),
    sa.Column('link_video', sa.String(length=255), nullable=False),
    sa.Column('material_content', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_path_id'), 'learning_path', ['id'], unique=False)
    op.create_table('learning_path_has_course',
    sa.Column('id_courses', sa.Integer(), nullable=False),
    sa.Column('id_learningpath', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_courses'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_learningpath'], ['learning_path.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_courses', 'id_learningpath')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_path_has_course')
    op.drop_index(op.f('ix_learning_path_id'), table_name='learning_path')
    op.drop_table('learning_path')
    # ### end Alembic commands ###
