"""setup create modulemodel

Revision ID: b616ebb2e30d
Revises: 4708fbd16f1f
Create Date: 2026-06-10 20:58:04.085218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b616ebb2e30d'
down_revision: Union[str, Sequence[str], None] = '4708fbd16f1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('id_module', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_reference', sa.Integer(), nullable=False),
    sa.Column('type_application', sa.Enum('CURSO', 'TRILHA', 'FORMACAO', name='typeapplication'), nullable=False),
    sa.Column('module_application_data', sa.Date(), nullable=False),
    sa.Column('module_application_ending', sa.Date(), nullable=False),
    sa.Column('module_duration', sa.String(length=30), nullable=False),
    sa.Column('total_spots', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('warning_message', sa.String(length=255), nullable=False),
    sa.Column('is_offer', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_module')
    )
    op.create_index(op.f('ix_modules_id_module'), 'modules', ['id_module'], unique=False)
    op.create_index(op.f('ix_modules_id_reference'), 'modules', ['id_reference'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modules_id_reference'), table_name='modules')
    op.drop_index(op.f('ix_modules_id_module'), table_name='modules')
    op.drop_table('modules')
    # ### end Alembic commands ###
