"""upgrade name column password to password hash

Revision ID: caeb5670b033
Revises: 9d18918905ba
Create Date: 2026-05-25 20:30:15.783989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caeb5670b033'
down_revision: Union[str, Sequence[str], None] = '9d18918905ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hash_password', sa.String(), nullable=False))
    op.drop_column('users', 'senha')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('senha', sa.VARCHAR(), nullable=False))
    op.drop_column('users', 'hash_password')
    # ### end Alembic commands ###
